<%
if request.Form("select") = "9a" then
response.Write("<center><img src=""resimler/9a.gif""></center>")
elseif request.Form("select") = "9b" then
response.Write("<center><img src=""resimler/9b.gif""></center>")
elseif request.Form("select") = "9c" then
response.Write("<center><img src=""resimler/9c.gif""></center>")
elseif request.Form("select") = "9d" then
response.Write("<center><img src=""resimler/9d.gif""></center>")
elseif request.Form("select") = "9e" then
response.Write("<center><img src=""resimler/9e.gif""></center>")
elseif request.Form("select") = "9f" then
response.Write("<center><img src=""resimler/9f.gif""></center>")
elseif request.Form("select") = "9g" then
response.Write("<center><img src=""resimler/9g.gif""></center>")
elseif request.Form("select") = "9h" then
response.Write("<center><img src=""resimler/9h.gif""></center>")
elseif request.Form("select") = "9i" then
response.Write("<center><img src=""resimler/9i.gif""></center>")
elseif request.Form("select") = "9k" then
response.Write("<center><img src=""resimler/9k.gif""></center>")
elseif request.Form("select") = "9l" then
response.Write("<center><img src=""resimler/9l.gif""></center>")
elseif request.Form("select") = "10fena" then
response.Write("<center><img src=""resimler/10fena.gif""></center>")
elseif request.Form("select") = "10fenb" then
response.Write("<center><img src=""resimler/10fenb.gif""></center>")
elseif request.Form("select") = "10fenc" then
response.Write("<center><img src=""resimler/10fenc.gif""></center>")
elseif request.Form("select") = "10fend" then
response.Write("<center><img src=""resimler/10fend.gif""></center>")
elseif request.Form("select") = "10sosa" then
response.Write("<center><img src=""resimler/10sosa.gif""></center>")
elseif request.Form("select") = "10sosb" then
response.Write("<center><img src=""resimler/10sosb.gif""></center>")
elseif request.Form("select") = "10sosc" then
response.Write("<center><img src=""resimler/10sosc.gif""></center>")
elseif request.Form("select") = "10sosd" then
response.Write("<center><img src=""resimler/10sosd.gif""></center>")
elseif request.Form("select") = "10tma" then
response.Write("<center><img src=""resimler/10tma.gif""></center>")
elseif request.Form("select") = "10tmb" then
response.Write("<center><img src=""resimler/10tmb.gif""></center>")
elseif request.Form("select") = "10tmc" then
response.Write("<center><img src=""resimler/10tmc.gif""></center>")
elseif request.Form("select") = "10tmd" then
response.Write("<center><img src=""resimler/10tmd.gif""></center>")
elseif request.Form("select") = "10tme" then
response.Write("<center><img src=""resimler/10tme.gif""></center>")
elseif request.Form("select") = "10tmf" then
response.Write("<center><img src=""resimler/10tmf.gif""></center>")
elseif request.Form("select") = "11fena" then
response.Write("<center><img src=""resimler/11fena.gif""></center>")
elseif request.Form("select") = "11fenb" then
response.Write("<center><img src=""resimler/11fenb.gif""></center>")
elseif request.Form("select") = "11fenc" then
response.Write("<center><img src=""resimler/11fenc.gif""></center>")
elseif request.Form("select") = "11fend" then
response.Write("<center><img src=""resimler/11fend.gif""></center>")
elseif request.Form("select") = "11fene" then
response.Write("<center><img src=""resimler/11fene.gif""></center>")
elseif request.Form("select") = "11fenf" then
response.Write("<center><img src=""resimler/11fenf.gif""></center>")
elseif request.Form("select") = "11sfa" then
response.Write("<center><img src=""resimler/11sfa.gif""></center>")
elseif request.Form("select") = "11sfb" then
response.Write("<center><img src=""resimler/11sfb.gif""></center>")
elseif request.Form("select") = "11sosa" then
response.Write("<center><img src=""resimler/11sosa.gif""></center>")
elseif request.Form("select") = "11sosb" then
response.Write("<center><img src=""resimler/11sosb.gif""></center>")
elseif request.Form("select") = "11sosc" then
response.Write("<center><img src=""resimler/11sosc.gif""></center>")
elseif request.Form("select") = "11stc" then
response.Write("<center><img src=""resimler/11stc.gif""></center>")
elseif request.Form("select") = "11tma" then
response.Write("<center><img src=""resimler/11tma.gif""></center>")
elseif request.Form("select") = "11tmb" then
response.Write("<center><img src=""resimler/11tmb.gif""></center>")
elseif request.Form("select") = "11tmc" then
response.Write("<center><img src=""resimler/11tmc.gif""></center>")
elseif request.Form("select") = "11tmd" then
response.Write("<center><img src=""resimler/11tmd.gif""></center>")
elseif request.Form("select") = "11tme" then
response.Write("<center><img src=""resimler/11tme.gif""></center>")
elseif request.Form("select") = "11tmf" then
response.Write("<center><img src=""resimler/11tmf.gif""></center>")
elseif request.Form("select") = "11tmg" then
response.Write("<center><img src=""resimler/11tmg.gif""></center>")
elseif request.Form("select") = "11tmh" then
response.Write("<center><img src=""resimler/11tmh.gif""></center>")
end if
%>